[package]
name = "config_parser_derive"
version = "0.1.0"
authors = ["Thang Pham <phamducthang1234@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.27"
quote = "1.0.9"
syn = "1.0.72"
