name: CD

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    name: Publishing ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            dependencies: "libssl-dev libasound2-dev libdbus-1-dev"
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            cross_arch: true
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            cross_arch: true
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install Linux dependencies
        if: matrix.dependencies
        run: sudo apt-get update && sudo apt-get install -y ${{ matrix.dependencies }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: ${{ matrix.cross_arch }}
          command: build
          args: --locked --release --target ${{ matrix.target }}

      - name: Package
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          case ${{ matrix.target }} in
          *-pc-windows-*)
            7z -y a hackernews_tui-${{ matrix.target }}.zip hackernews_tui.exe
            sha256sum hackernews_tui-${{ matrix.target }}.zip > hackernews_tui-${{ matrix.target }}.sha256
            ;;
          *)
            tar czvf hackernews_tui-${{ matrix.target }}.tar.gz hackernews_tui
            shasum -a 256 hackernews_tui-${{ matrix.target }}.tar.gz > hackernews_tui-${{ matrix.target }}.sha256
            ;;
          esac;

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/${{ matrix.target }}/release/hackernews_tui-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
